### PR TITLE
Add apisix.

### PR DESCRIPTION
**Pull request by Azkick3r**
Add apisix.

### CODE REVIEW

**Comment by goafabric** [comment]
looks already good and cool that you've found a way to have the routes as yaml file
2 things .. there is somewhere already gss-*-*docker somewhere .. should not be here or switch to private repo

and the multi tenancy oidc is currently static, with explicit routes per tenant ( 0 && 5)
while this is a good starting point, they should be dynamic l8r on, with inference from the url,
maybe this is easily possible via a regex  e.g.:
discovery: https://kubernetes/oidc/realms/tenant-{regix-inferred-from-path}

and for the tenant id, it should be at the end of the path if possible:
/core/5

but i guess thats all work in progress now ... 
Happy to see that it seems to generally work

**Comment by Azkick3r** [comment]
> looks already good and cool that you've found a way to have the routes as yaml file 2 things .. there is somewhere already gss-*-*docker somewhere .. should not be here or switch to private repo
> 
> and the multi tenancy oidc is currently static, with explicit routes per tenant ( 0 && 5) while this is a good starting point, they should be dynamic l8r on, with inference from the url, maybe this is easily possible via a regex e.g.: discovery: [https://kubernetes/oidc/realms/tenant-{regix-inferred-from-path}](https://kubernetes/oidc/realms/tenant-%7Bregix-inferred-from-path%7D)
> 
> and for the tenant id, it should be at the end of the path if possible: /core/5
> 
> but i guess thats all work in progress now ... Happy to see that it seems to generally work

Hi, for the first thing, if you are referring to the core-service docker image, it is only for test, I wanted to see if the headers from oidc are sent to the service and how do they look like and for the second thing, I found this link for dynamic routing https://api7.ai/blog/dynamic-routing-based-on-user-credentials , that should be just what we need.

**Comment by goafabric** [comment]
> > looks already good and cool that you've found a way to have the routes as yaml file 2 things .. there is somewhere already gss-*-*docker somewhere .. should not be here or switch to private repo
> > and the multi tenancy oidc is currently static, with explicit routes per tenant ( 0 && 5) while this is a good starting point, they should be dynamic l8r on, with inference from the url, maybe this is easily possible via a regex e.g.: discovery: [https://kubernetes/oidc/realms/tenant-{regix-inferred-from-path}](https://kubernetes/oidc/realms/tenant-%7Bregix-inferred-from-path%7D)
> > and for the tenant id, it should be at the end of the path if possible: /core/5
> > but i guess thats all work in progress now ... Happy to see that it seems to generally work
> 
> Hi, for the first thing, if you are referring to the core-service docker image, it is only for test, I wanted to see if the headers from oidc are sent to the service and how do they look like and for the second thing, I found this link for dynamic routing https://api7.ai/blog/dynamic-routing-based-on-user-credentials , that should be just what we need.

yeah i

**Comment by goafabric** [comment]
yeah i pretty much thought of this .. wasnt expecting an answert so soon .. thx 4 the excellent work
i will be on vacaction from now on, cu soon

**Pull request closed without merging**
